version: '3.5'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=minecraft
      - TZ=Europe/Paris
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 80:80
    environment:
      - PMA_HOST=mariadb
    container_name: phpmyadmin

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    volumes:
      - ./data/minecraft/server:/data
      - ./build/reobfShadowJar/output.jar:/mods/authmod.jar
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - ONLINE_MODE=FALSE
      - TYPE=FORGE
      - FORGE_INSTALLER_URL=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.2-31.1.18/forge-1.15.2-31.1.18-installer.jar
