
#Server configuration settings
[server]
	#Enable or disable the /login command. If disabled, the server will be opened to everyone).
	enableLogin = false
	#delay in seconds a player can authenticate before being automatically kicked from the server.
	#Range: 1 ~ 1024
	delay = 60
	#lang file to use
	#Allowed Values: EN_US, FR_FR, ES_ES
	language = "EN_US"
	#Whitelisted commands (can be used without being logged)
	whitelist = ["register", "login", "logged", "help"]
	#Identifier must be provided for registration and authentication
	identifierRequired = false
	#Enable or disable the /register command.
	enableRegister = false
	#Enable or disable the /changepassword command.
	enableChangePassword = false
	#The way you want to store player's data, choose between 'database' or 'file'. If the strategy is unknown, the server will be open for everyone.
	#Allowed Values: FILE, DATABASE, NONE
	dataSource = "FILE"

[Database]
	#Column for UUID
	colummUuid = "uuid"
	#SQL dialect
	dialect = "mariadb"
	#Column for the encrypted password
	columnPassword = "password"
	#Column telling whether the player is banned
	columnBan = "banned"
	#Name of the database
	database = "minecraft"
	#Database users's password
	password = "user"
	#Column for the username
	colummUsername = "username"
	#JDBC driver to use
	driver = "org.mariadb.jdbc.Driver"
	#Port to be used
	#Range: 1024 ~ 65535
	port = 3306
	#Server hosting the database
	host = "localhost"
	#Database user
	user = "user"
	#Column for the identifier
	columnIdentifier = "email"
	#Table to be used
	table = "players"

[I18n]
	#Wrong password. Please try again.
	wrongPassword = ""
	#yes
	loggedYes = ""
	#Your username does not correspond to your credentials.
	loginWrongusername = ""
	#You are registered and authenticated, have fun!
	registerSuccess = ""
	#/changepassword <old_password> <new_password> <new_password> - Change your password.
	changepasswordUsage = ""
	#/register <email> <password> <password>- Be careful when choosing it, you'll be asked to login each time you play.
	registerUsage = ""
	#Wake up, you have only %s seconds to log in.
	wakeUp = ""
	#Password changed!
	changepasswordSuccess = ""
	#Something was wrong. Please contact the admins.
	error = ""
	#/logged - tells you whether you are authenticated or not
	loggedUsage = ""
	#Someone has already registered with the username %s.
	registerExist = ""
	#Have fun!
	loginSuccess = ""
	#The password confirmation doesn't match. Try again.
	wrongPasswordConfirmation = ""
	#no
	loggedNo = ""
	#%s is not registered on this server.
	loginNotfound = ""
	#New password should be different than the previous one.
	changepasswordSamepassword = ""
	#Wrong UUID. Please be sure you use the same UUID when you registered your account.
	loginWronguuid = ""
	#You've been banned. Please contact the admins.
	banned = ""
	#Use /register to sign up or /login to sign in.
	welcome = ""
	#/login <email> <password> - Allows you to authenticate on the server
	loginUsage = ""

